name: ghost_actor

on: [ push ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-task
      - uses: actions-rs/cargo@v1
        with:
          command: task
          args: test
