name: ghost_actor

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          windows-latest,
        ]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/neonphog/cargo-task.git --branch remove-canonicalize
      - uses: actions-rs/cargo@v1
        with:
          command: task
          args: test
